### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pietervdvn** [openplannerteam/itinero-transit#5]
- [x] Filter pareto-optimal points when CSP is done
- [x] Add transfers
- [x] Decouple downloading the data and running the algorithm
- [x] Add fixed tests with in-git JSONs
- [x] Integrate Itinero for intermodal transfers from stop to stop
- [x] Add Intermodal transfers
- [x] Optimize to the metal
  - [x] Do a forward EAS first, to bound the search space (fix EAS with trips first)
  - [ ] Keep track of known solutions to bound solutions which are to long
- [ ] [Create a production-ready API](https://github.com/anyways-open/itinero-transit-server)
  - [x] For station to station, within one operator
  - [ ] For interoperator
- [ ] Include other services (The Big Belgian Four)
  -  [x] Pick an ontology to use: [LinkedConnections](http://semweb.mmlab.be/ns/linkedconnections#) by Pieter Colpaert of course
  -  [x] Fix JSON-LD
  - [x] Integrate Json-LD for the SNCB
  - [x] Integrate De Lijn
  - [ ] Abstract further to work with catalogs: BLOCKED: [see this issue](https://github.com/openplannerteam/planner.js/issues/11)
  - [ ] Integrate TEC
  - [ ] Integrate MIVB/STIB
- [x] Figure out a nice heuristic to get an estimated time to travel
  - [x] (2* EAS?)
  - [x] Include in profile
- [ ] Bundle preferences such as transfer times, intermodal options (cycling, bluebike) in a profile
    - [x] Bundle basic preferences in a profile
    - [ ] Make the profile serializable
- [ ] Exploit the long tail:
  - [ ] Get linked connections for small shuttles into OSM (Contact Polyglot, workout tagging scheme)
  - [ ] Setup a linked connection server for them
  - [ ] Promote this in Be
- [ ] Host a linked-connection server for small shuttle busses
- [x] Restructure the project according to C# conventions
- [x] Update the documentation

Long term:

- [ ] Have hypermobility
- [ ] Include cycling as option
   - [ ] Specify availability of bicycles (e.g. at home and certain stations)
   - [ ] Specify having a foldable bike
   - [ ] Include shared bikes as an option
   - [ ] Include bluebike
